[project]
name = "cnpm-be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Khanh-12-felix", email = "hathaikhanh0@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
cnpm-be = "cnpm_be:main"

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"
